# Generated by Django 4.2.7 on 2023-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_healthhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhistory',
            name='doctor',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
