# Generated by Django 4.2.6 on 2023-11-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_host_room_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='remember_me',
            new_name='guest_can_pause',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='phd',
            new_name='votes_to_skip',
        ),
    ]
