# Generated by Django 4.2.6 on 2023-11-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_remember_me_room_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pause',
            new_name='remember_me',
        ),
    ]
