# Generated by Django 4.2.6 on 2023-11-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_guest_can_pause_room_remember_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skip',
            new_name='phd',
        ),
    ]
