# Generated by Django 4.2.6 on 2023-11-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_votes_to_skip_room_phd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='phd',
            new_name='votes_to_skip',
        ),
    ]
